print ("=======================================")
print ("Program Biodata Sederhana dengan Python")
print ("=======================================")
(nama   = "Adelia Safira")
(Hobi   = "Olahraga")
(alamat = "Tengkong-tengkong, sungai jariang")
(Kota   = "Lubuk Basung")
print ("Nama Lengkap:", nama)
print ("Alamat      :",alamat, "\n            Kota", Kota)
print ("Hobi        :", hobi)
print ("=======================================")
