print ("========================================")
print ("Program Biodata Sederhana Dengan Python")
print ("========================================")
(nama   = "Resa Kairani Putri")
(Hobi   = "Menggambar")
(alamat = "Padang Sawah")
(kota   = "pasaman")
print ("Nama Lengkap:", nama)
print ("Alamat      :",alamat, "\n              Kota", Kota)
print ("Hobi        :", hobi)
print ("========================================")
